version: 2

sources:
  - name: FRFA
    description: A clone of a PRFA database.
    database: FRFA
    tables:
      - name: POSITIONS_DATA
        description: Raw positions data.
        columns:
          - name: "Valuation_Date"
            description: Valuation date for the account mentioned.
            tests:
              - not_null
          - name: "Account_ID_FA"
            description: FA GIO account number.
            tests:
              - not_null
          - name: "FA_Asset_Group" 
            description: Asset class for the asset.
            tests:
              - not_null
              - accepted_values:
                  values: ['S','P','UN','B','FT','MR','FE','CF','CL','CB','IV','MF','IT','GI','CU','CC','CT','FB','W','G','CV','CA','FS']   
          - name: "Price_Code"
            description: Price code determines how Market value for an asset is calculated.
            tests:
              - not_null
              - accepted_values:
                  values: ['S','B','X','I','D','F']  
      - name: TRANSACTION_DATA
        description: Raw transactions data.
        columns:
          - name: "Account_ID_FA"
            description: FA GIO account number.
            tests:
              - not_null
      - name: VALUATION_DATA
        description: Raw Valuation data.
        columns:
          - name: "Class_of_Shares"
            description: Class for shares for the account.
            tests:
              - not_null