
SELECT 
"Amortization (Base)" as Amortization_Base,
 "Income Subcategory" as Income_Subcategory,
 "Maturity Date" as Maturity_Date,
 "Country of Risk Name" as Country_of_Risk_Name,
 "Effect on Redemptions (Local)" as Effect_on_Redemptions_Local,
 "Exchange Rate" as Exchange_Rate,
 "Realized FX Gain/Loss on Amort (Local)" as Realized_FX_GainLoss_on_Amort_Local,
 "Income Category Description" as Income_Category_Description,
 "Unrealized FX G/L on Principal" as Unrealized_FX_GL_on_Principal,
 "Valoren ID" as Valoren_ID,
 "Trade Amount (Base)" as Trade_Amount_Base,
 "Account Base Country" as Account_Base_Country,
 "Cumulative NAV Impact" as Cumulative_NAV_Impact,
 "Income Subcategory Description" as Income_Subcategory_Description,
 "Instrument ID" as Instrument_ID,
 "LEI Identifier" as LEI_Identifier,
 "Interest Bought/Sold (Base)" as Interest_BoughtSold_Base,
 "Issue Currency Name" as Issue_Currency_Name,
 "Security Category Segment Description" as Security_Category_Segment_Description,
 "Settlement Currency" as Settlement_Currency,
 "Price Code" as Price_Code,
 "Account Base Country Name" as Account_Base_Country_Name,
 "Effect on Redemptions Exchanged (Local)" as Effect_on_Redemptions_Exchanged_Local,
 "Fund Type" as Fund_Type,
 "Price Code Description" as Price_Code_Description,
 "Security Category Description" as Security_Category_Description,
 "Trading Currency Name" as Trading_Currency_Name,
 "External Reference Number" as External_Reference_Number,
 "Realized Exchange Gain Loss" as Realized_Exchange_Gain_Loss,
 "Realized Gain/Loss Net of Amortization" as Realized_GainLoss_Net_of_Amortization,
 "Report Group Type" as Report_Group_Type,
 "Security Category Industry Description" as Security_Category_Industry_Description,
 "Settlement Currency Name" as Settlement_Currency_Name,
 "Realized Gain/Loss (Base)" as Realized_GainLoss_Base,
 "Transaction Supercategory Code" as Transaction_Supercategory_Code,
 "OPCCT Contract Type" as OPCCT_Contract_Type,
 "Settlement Date (Actual)" as Settlement_Date_Actual,
 "Account Indicator" as Account_Indicator,
 "CUSIP" as CUSIP,
 "Class of Shares" as Class_of_Shares,
 "Realized Exchange Gain/Loss on Debt (Local)" as Realized_Exchange_GainLoss_on_Debt_Local,
 "Realized FX Gain/Loss on Amort Total (Local)" as Realized_FX_GainLoss_on_Amort_Total_Local,
 "Ticker Symbol" as Ticker_Symbol,
 "Trade Base FX Rate" as Trade_Base_FX_Rate,
 "Trading Currency" as Trading_Currency,
 "Transaction Supercategory Name" as Transaction_Supercategory_Name,
 "Net NAV Impact" as Net_NAV_Impact,
 "% NAV Impact for Realized Capital Gain/Loss" as pct_NAV_Impact_for_Realized_Capital_GainLoss,
 "Broker Commission (Base)" as Broker_Commission_Base,
 "Master Transaction ID" as Master_Transaction_ID,
 "Asset ID" as Asset_ID,
 "FA Asset Group" as FA_Asset_Group,
 "Memo Number" as Memo_Number,
 "Realized Exchange Gain/Loss Total (Local)" as Realized_Exchange_GainLoss_Total_Local,
 "SEDOL" as SEDOL,
 "Transaction Subcategory Code" as Transaction_Subcategory_Code,
 "Settle Amount (Local)" as Settle_Amount_Local,
 "Transaction Description" as Transaction_Description,
 "Realized Gain/Loss Total (Base)" as Realized_GainLoss_Total_Base,
 "Account Base Currency Name" as Account_Base_Currency_Name,
 "Amortized Cost (Base)" as Amortized_Cost_Base,
 "Prior Participant Equity (Base)" as Prior_Participant_Equity_Base,
 "Reuters RIC" as Reuters_RIC,
 "Underlying Bloomberg ticker" as Underlying_Bloomberg_ticker,
 "Security Category" as Security_Category,
 "Security Category Segment" as Security_Category_Segment,
 "Capital Stock in Excess of PAR" as Capital_Stock_in_Excess_of_PAR,
 "Unrealized FX G/L on Income" as Unrealized_FX_GL_on_Income,
 "Coupon Rate" as Coupon_Rate,
 "Group Allocation" as Group_Allocation,
 "Income Category" as Income_Category,
 "Transaction Code Description" as Transaction_Code_Description,
 "Capital Stock at Par (Base)" as Capital_Stock_at_Par_Base,
 "FA Asset Group Name" as FA_Asset_Group_Name,
 "Fund Category" as Fund_Category,
 "Group Allocation Classes" as Group_Allocation_Classes,
 "ISIN" as ISIN,
 "Transaction Subcategory Name" as Transaction_Subcategory_Name,
 "OTC Broker" as OTC_Broker,
 "Reversal XREF Memo Number" as Reversal_XREF_Memo_Number,
 "Settlement Date (Contractual)" as Settlement_Date_Contractual,
 "Effect on Subscriptions (Local)" as Effect_on_Subscriptions_Local,
 "Realized Capital Gain Loss" as Realized_Capital_Gain_Loss,
 "Master Security ID" as Master_Security_ID,
 "Principal Amount (Base)" as Principal_Amount_Base,
 "Interest Purchases/Sold (Local)" as Interest_PurchasesSold_Local,
 "Broker Name (Executing)" as Broker_Name_Executing,
 "Country of Taxation Name" as Country_of_Taxation_Name,
 "Realized Exchange G/L on Currencies (Local)" as Realized_Exchange_GL_on_Currencies_Local,
 "Security Category Sector Description" as Security_Category_Sector_Description,
 "Broker (Executing)" as Broker_Executing,
 "Cost (Base)" as Cost_Base,
 "Effect on Subscriptions Exchanged (Local)" as Effect_on_Subscriptions_Exchanged_Local,
 "Security Category Sector" as Security_Category_Sector,
 "Security Number (Full)" as Security_Number_Full,
 "Asset Supercategory Code" as Asset_Supercategory_Code,
 "Long/Short Indicator" as LongShort_Indicator,
 "Rec/Pay Realized FX G/L to Date (Local)" as RecPay_Realized_FX_GL_to_Date_Local,
 "Security Qualifier" as Security_Qualifier,
 "Tran Aver Unit Cost (Base)" as Tran_Aver_Unit_Cost_Base,
 "Income Currency" as Income_Currency,
 "Income Currency Name" as Income_Currency_Name,
 "Country of Taxation" as Country_of_Taxation,
 "Principal Amount (Local)" as Principal_Amount_Local,
 "Realized FX Gain/Loss Recvbl/Paybl (Base)" as Realized_FX_GainLoss_RecvblPaybl_Base,
 "Tran Class Description" as Tran_Class_Description,
 "Price (Local)" as Price_Local,
 "Trade Expense" as Trade_Expense,
 "Asset Subcategory Name" as Asset_Subcategory_Name,
 "Transaction Class Code" as Transaction_Class_Code,
 "Issue Currency" as Issue_Currency,
 "Realized Trade FX Gain/Loss (Local)" as Realized_Trade_FX_GainLoss_Local,
 "Shares/Par Outstanding" as SharesPar_Outstanding,
 "Trade Expense (Base)" as Trade_Expense_Base,
 "Account ID (FA)" as Account_ID_FA,
 "Asset Subcategory Code" as Asset_Subcategory_Code,
 "Broker Commission (Local)" as Broker_Commission_Local,
 "Contra Expense Indicator" as Contra_Expense_Indicator,
 "Northern Trust Security Identifier" as Northern_Trust_Security_Identifier,
 "Master Account ID" as Master_Account_ID,
 "Account Group ID" as Account_Group_ID,
 "Effective Date" as Effective_Date,
 "NAV Impact for Realized Capital Gain/Loss" as NAV_Impact_for_Realized_Capital_GainLoss,
 "Net Assets (Base)" as Net_Assets_Base,
 "Country of Risk" as Country_of_Risk,
 "Price (Base)" as Price_Base,
 "Security Number" as Security_Number,
 "Settle Amount (Base)" as Settle_Amount_Base,
 "Shares/Par" as SharesPar,
 "Cumulative % NAV Impact" as Cumulative_pct_NAV_Impact,
 "Security Category Industry" as Security_Category_Industry,
 "Transaction Code" as Transaction_Code,
 "Account Base Currency" as Account_Base_Currency,
 "Cost (Local)" as Cost_Local,
 "Effect on Dividends Reinvested (Local)" as Effect_on_Dividends_Reinvested_Local,
 "Income Amount (Local)" as Income_Amount_Local,
 "Asset Supercategory Name" as Asset_Supercategory_Name,
 "Realized Non-Bifurcated Exchange Gain/Loss" as Realized_NonBifurcated_Exchange_GainLoss,
 "Ex-Date Shares" as ExDate_Shares,
 "General Ledger Code" as General_Ledger_Code,
 "Income Amount (Base)" as Income_Amount_Base,
 "Security Description (Short)" as Security_Description_Short,
 "Trade Date" as Trade_Date,
 "CINS" as CINS,
 "Equalization Bought/Sold (Local)" as Equalization_BoughtSold_Local,
 "Generated Transaction Code" as Generated_Transaction_Code,
 "Inflation Comp Purch/Sold (Local)" as Inflation_Comp_PurchSold_Local,
 "Prior Price (Base)" as Prior_Price_Base,
 "Realized Exchange Gain/Loss on Income (Local)" as Realized_Exchange_GainLoss_on_Income_Local,
 "Security Description (Long)" as Security_Description_Long
FROM {{ source('FRFA', 'TRANSACTION_DATA') }}