
SELECT
"% NAV Impact for Expenses Charged" as pct_NAV_Impact_for_Expenses_Charged,
 "Accrued Gross Withholding (Basis)" as Accrued_Gross_Withholding_Basis,
 "Accrued Gross Withholding (Local)" as Accrued_Gross_Withholding_Local,
 "Country of Risk" as Country_of_Risk,
 "Earned Amortization (Base)" as Earned_Amortization_Base,
 "FA Asset Group (Expanded)" as FA_Asset_Group_Expanded,
 "Group Allocation" as Group_Allocation,
 "Price Source" as Price_Source,
 "Issue Date" as Issue_Date,
 "Price Code" as Price_Code,
 "LEI Identifier" as LEI_Identifier,
 "Months to Maturity" as Months_to_Maturity,
 "Price (Local)" as Price_Local,
 "Unrealized Income Exchange Gain/Loss (Local)" as Unrealized_Income_Exchange_GainLoss_Local,
 "First Income Date" as First_Income_Date,
 "Account Indicator" as Account_Indicator,
 "Counterparty" as Counterparty,
 "Reuters RIC" as Reuters_RIC,
 "Security Category Industry Description" as Security_Category_Industry_Description,
 "Underlying Bloomberg ticker" as Underlying_Bloomberg_ticker,
 "Unrealized Result" as Unrealized_Result,
 "Issue Currency" as Issue_Currency,
 "Prior Accrued Income/Expense (Local)" as Prior_Accrued_IncomeExpense_Local,
 "Accrued Net Withholding (Base)" as Accrued_Net_Withholding_Base,
 "Exchange Rate" as Exchange_Rate,
 "% of NAV" as pct_of_NAV,
 "Custodian" as Custodian,
 "Group Allocation Classes" as Group_Allocation_Classes,
 "Market Value Settled (Base)" as Market_Value_Settled_Base,
 "Market Yield" as Market_Yield,
 "Shares/Par Outstanding" as SharesPar_Outstanding,
 "Unrealized Market Exchange Gain/Loss (Local)" as Unrealized_Market_Exchange_GainLoss_Local,
 "Unrealized Mkt Gain/Loss Change" as Unrealized_Mkt_GainLoss_Change,
 "Fair Value Price Processed" as Fair_Value_Price_Processed,
 "Report Group Type" as Report_Group_Type,
 "Account Base Currency" as Account_Base_Currency,
 "Bloomberg Unique ID" as Bloomberg_Unique_ID,
 "Earned Income (Base)" as Earned_Income_Base,
 "Income as Expense Flag" as Income_as_Expense_Flag,
 "Prior Accrued Income/Expense (Base)" as Prior_Accrued_IncomeExpense_Base,
 "SEDOL" as SEDOL,
 "Security Number (Full)" as Security_Number_Full,
 "Security Category Description" as Security_Category_Description,
 "Security Category Sector" as Security_Category_Sector,
 "Strike Price" as Strike_Price,
 "Unrealized Exchange G/L (Includes Stocks)" as Unrealized_Exchange_GL_Includes_Stocks,
 "Net Assets (Base)" as Net_Assets_Base,
 "% NAV Impact for Income Received" as pct_NAV_Impact_for_Income_Received,
 "Accrued Interest NAV%" as Accrued_Interest_NAVpct,
 "Cost (Local)" as Cost_Local,
 "Creation Price" as Creation_Price,
 "GIC Industry Groups - S&P/MSCI" as GIC_Industry_Groups__SPMSCI,
 "Memo Number" as Memo_Number,
 "Shares Outstanding - Total" as Shares_Outstanding__Total,
 "Shares/Par" as SharesPar,
 "GIC Industries - S&P/MSCI" as GIC_Industries__SPMSCI,
 "Market Value TNA Percentage" as Market_Value_TNA_Percentage,
 "Price (Base)" as Price_Base,
 "SEDOL Underlying" as SEDOL_Underlying,
 "Security Category" as Security_Category,
 "Unrealized Mkt Gain/Loss To Date (Base)" as Unrealized_Mkt_GainLoss_To_Date_Base,
 "Pay Date" as Pay_Date,
 "% NAV Impact for Accrued Income" as pct_NAV_Impact_for_Accrued_Income,
 "Asset Supercategory Name" as Asset_Supercategory_Name,
 "Holdings Average Cost (Local)" as Holdings_Average_Cost_Local,
 "Instrument ID" as Instrument_ID,
 "Market Value Traded (Local)" as Market_Value_Traded_Local,
 "Reclaim Amount (Local)" as Reclaim_Amount_Local,
 "S&P Rating" as SP_Rating,
 "Security Category Sector Description" as Security_Category_Sector_Description,
 "Ticker Symbol" as Ticker_Symbol,
 "Income Subcategory Description" as Income_Subcategory_Description,
 "Issuer Name" as Issuer_Name,
 "Investment Manager ID" as Investment_Manager_ID,
 "Unrealized Market Gain/Loss (Base)" as Unrealized_Market_GainLoss_Base,
 "Amortized Cost (Base)" as Amortized_Cost_Base,
 "Fund Type" as Fund_Type,
 "GIC Econ Sectors - S&P/MSCI" as GIC_Econ_Sectors__SPMSCI,
 "Market Value Offer (Base)" as Market_Value_Offer_Base,
 "NAV Impact for Prior Accrued Income" as NAV_Impact_for_Prior_Accrued_Income,
 "GIC Sub Industries - S&P/MSCI" as GIC_Sub_Industries__SPMSCI,
 "Income Currency" as Income_Currency,
 "OTC Flag" as OTC_Flag,
 "Price Code Name" as Price_Code_Name,
 "Unrealized Gain/Loss Total (Base)" as Unrealized_GainLoss_Total_Base,
 "Valuation Date" as Valuation_Date,
 "Unrealized Exchange Gain/Loss Total (Base)" as Unrealized_Exchange_GainLoss_Total_Base,
 "Prior Amortization Accrual (Base)" as Prior_Amortization_Accrual_Base,
 "Accrued Gross Withholding (Base)" as Accrued_Gross_Withholding_Base,
 "Earned Income/Expenses Charged (Local)" as Earned_IncomeExpenses_Charged_Local,
 "Ex-Date" as ExDate,
 "Prior Cancellation Amount (Base)" as Prior_Cancellation_Amount_Base,
 "Accrued Gross Reclaim (Base)" as Accrued_Gross_Reclaim_Base,
 "Accrued Net Income (Base)" as Accrued_Net_Income_Base,
 "Contract Size (Full)" as Contract_Size_Full,
 "GIC Industry Groups Description - S&P/MSCI" as GIC_Industry_Groups_Description__SPMSCI,
 "Variation Margin (Base)" as Variation_Margin_Base,
 "Class of Shares" as Class_of_Shares,
 "Prior Participant Equity (Base)" as Prior_Participant_Equity_Base,
 "Variation Margin (Local)" as Variation_Margin_Local,
 "Issue Type" as Issue_Type,
 "Fitch Rating" as Fitch_Rating,
 "NAV Impact for Expenses Charged" as NAV_Impact_for_Expenses_Charged,
 "Primary Exchange Code" as Primary_Exchange_Code,
 "Security Category Segment" as Security_Category_Segment,
 "Year/Month" as YearMonth,
 "NAV Impact for Accrued Income" as NAV_Impact_for_Accrued_Income,
 "Security Qualifier" as Security_Qualifier,
 "Unrealized Mkt Gain/Loss From Date (Base)" as Unrealized_Mkt_GainLoss_From_Date_Base,
 "Account Base Country" as Account_Base_Country,
 "Accrued Net Income (Local)" as Accrued_Net_Income_Local,
 "Country of Incorporation" as Country_of_Incorporation,
 "FA Asset Group Name (Expanded)" as FA_Asset_Group_Name_Expanded,
 "Prior Creation Amount (Base)" as Prior_Creation_Amount_Base,
 "Asset Subcategory Code" as Asset_Subcategory_Code,
 "Cost (Base)" as Cost_Base,
 "FX Forward Rate" as FX_Forward_Rate,
 "GIC Industries Description - S&P/MSCI" as GIC_Industries_Description__SPMSCI,
 "General Ledger Code" as General_Ledger_Code,
 "Market Capitalization" as Market_Capitalization,
 "Market Valued and Accrued Interest NAV %" as Market_Valued_and_Accrued_Interest_NAV_pct,
 "Market Value Traded (Base)" as Market_Value_Traded_Base,
 "Price Type" as Price_Type,
 "Security Description (Short)" as Security_Description_Short,
 "Unrealized Exchange Gain/Loss on Amortization" as Unrealized_Exchange_GainLoss_on_Amortization,
 "Valoren ID" as Valoren_ID,
 "Market Value Settled (Local)" as Market_Value_Settled_Local,
 "Accrued Income/Expense (Local)" as Accrued_IncomeExpense_Local,
 "Asset Supercategory Code" as Asset_Supercategory_Code,
 "Cancellation Value (Base)" as Cancellation_Value_Base,
 "Prime Broker" as Prime_Broker,
 "Asset ID" as Asset_ID,
 "Currency Contract ID" as Currency_Contract_ID,
 "Days / Share class" as Days__Share_class,
 "FA Asset Group Name" as FA_Asset_Group_Name,
 "Holdings Average Unit Cost (Base)" as Holdings_Average_Unit_Cost_Base,
 "Long/Short Indicator" as LongShort_Indicator,
 "Security Identifier" as Security_Identifier,
 "Total Market Value (Base)" as Total_Market_Value_Base,
 "Contra Expense Indicator" as Contra_Expense_Indicator,
 "% NAV Impact for Prior Accrued Income" as pct_NAV_Impact_for_Prior_Accrued_Income,
 "Amortization (Local)" as Amortization_Local,
 "Amortized Cost (Local)" as Amortized_Cost_Local,
 "Asset Subcategory Name" as Asset_Subcategory_Name,
 "Bloomberg Global Identifier" as Bloomberg_Global_Identifier,
 "CUSIP" as CUSIP,
 "Exchange Rate Type" as Exchange_Rate_Type,
 "GIC Sub Industries Description - S&P/MSCI" as GIC_Sub_Industries_Description__SPMSCI,
 "Income Category" as Income_Category,
 "Maturity Date" as Maturity_Date,
 "Contract Type" as Contract_Type,
 "Currency Market (Local)" as Currency_Market_Local,
 "Exchange Rate Source" as Exchange_Rate_Source,
 "Moody Rating" as Moody_Rating,
 "Original Face" as Original_Face,
 "Security Description (Long)" as Security_Description_Long,
 "Fund Category" as Fund_Category,
 "Income Received (Base)" as Income_Received_Base,
 "Unrealized Gain/Loss Total (Local)" as Unrealized_GainLoss_Total_Local,
 "Price Time" as Price_Time,
 "NAV Impact for Income Received" as NAV_Impact_for_Income_Received,
 "Accrual Method Code" as Accrual_Method_Code,
 "Accrued Net Amortization (Base)" as Accrued_Net_Amortization_Base,
 "Amortization (Base)" as Amortization_Base,
 "Bond Payment Frequency" as Bond_Payment_Frequency,
 "Country of Taxation" as Country_of_Taxation,
 "Security Category Segment Description" as Security_Category_Segment_Description,
 "Amortization Sold (Base)" as Amortization_Sold_Base,
 "Contract Type Name" as Contract_Type_Name,
 "Exchange Rate Time" as Exchange_Rate_Time,
 "GIC Econ Sectors Description - S&P/MSCI" as GIC_Econ_Sectors_Description__SPMSCI,
 "Security Number" as Security_Number,
 "Put/Call Flag" as PutCall_Flag,
 "% NAV Impact for Earned Amortization" as pct_NAV_Impact_for_Earned_Amortization,
 "% NAV Impact for Earned Income" as pct_NAV_Impact_for_Earned_Income,
 "Account ID (FA)" as Account_ID_FA,
 "Bond Principal" as Bond_Principal,
 "Shares/Par Settled" as SharesPar_Settled,
 "Short Position - Income Treatment" as Short_Position__Income_Treatment,
 "Accrued Interest Days" as Accrued_Interest_Days,
 "NAV Impact for Earned Income" as NAV_Impact_for_Earned_Income,
 "Prior Valuation Date" as Prior_Valuation_Date,
 "Security Category Industry" as Security_Category_Industry,
 "Total Market Value (Local)" as Total_Market_Value_Local,
 "Cost (Basis)" as Cost_Basis,
 "Market Value (Base) NAV" as Market_Value_Base_NAV,
 "NAV Impact for Earned Amortization" as NAV_Impact_for_Earned_Amortization,
 "Price Offer (Base)" as Price_Offer_Base,
 "Underlying Security" as Underlying_Security,
 "Coupon Rate" as Coupon_Rate,
 "Trading Currency" as Trading_Currency,
 "Variation Margin Sum (Base)" as Variation_Margin_Sum_Base,
 "Accrued Income/Expense (Base)" as Accrued_IncomeExpense_Base,
 "Duration - Modified" as Duration__Modified,
 "Earned Expense (Base)" as Earned_Expense_Base,
 "Expenses Paid (Base)" as Expenses_Paid_Base,
 "Income Category Description" as Income_Category_Description,
 "Shareholder Equity (Base)" as Shareholder_Equity_Base,
 "Expiration Date" as Expiration_Date,
 "Accrued Gross Reclaim (Basis)" as Accrued_Gross_Reclaim_Basis,
 "Accrued Net Withholding (Basis)" as Accrued_Net_Withholding_Basis,
 "Account Group ID" as Account_Group_ID,
 "CINS" as CINS,
 "FA Asset Group" as FA_Asset_Group,
 "ISIN" as ISIN,
 "Income Subcategory" as Income_Subcategory,
 "Withholding Rate Accrued (Local)" as Withholding_Rate_Accrued_Local,
 "Expenses Charged (Base)" as Expenses_Charged_Base
FROM {{ source('FRFA', 'POSITIONS_DATA') }}
